# Generated by Django 4.0.1 on 2022-04-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
